title: Amit Pawar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Into finding answers | Likes to Code 
  <br><br>
  I share stuff I have been working on over here. 
  <br><br>
  <a href="https://www.linkedin.com/in/amittppawar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
